### ISSUE TITLE
Can't change avatar

### ISSUE THREAD

**Issue by Janeator** [Northcodeno/cobaltvault.no#2]
Attempting to upload a new avatar will result in not doing so. It will still display a "success!" message tho.

**Comment by Jenjen1324** [comment]
Cannot reproduce, tried both with .png and .jpg. Please note that these are the only supported formats!

**Comment by Janeator** [comment]
I belive I was trying to upload the same avatar I'm using here. I'll try to remember to give yuo the file, but it's png.

**Comment by Jenjen1324** [comment]
Ok managed to reproduce, I'll look into it

**Comment by Jenjen1324** [comment]
This is no longer an issue with the rebuilt site.
