### ISSUE TITLE
Cannot open files

### ISSUE THREAD

**Issue by GAMBL3R** [Northcodeno/cobaltvault.no#8]
whenever I download ANY file from cobalt vault and I attempt to open it, immediately I get an error that says the file is invalid. I tried downloading the same file type (.zip) from other locations and it worked perfectly. as far as I can tell it isn't my computer, otherwise I wouldn't have bothered you. 
thx-GAMBL3R

**Comment by Plazmaz** [comment]
I can't reproduce this, any specific files you've tried to download?

**Comment by Jenjen1324** [comment]
This is probably specific to some projects. Either the author didn't upload his files correctly or there's an error in our storage

**Comment by GAMBL3R** [comment]
I don't think so, I tried several and all of those I tried had been
downloaded several times before. So I guess it's an error on my end :/ I
checked my firewall settings and messed with the website cookies I had and
I managed to get a couple maps  downloaded...I'll keep trying

**Comment by Jenjen1324** [comment]
Can you try to clear your cookies and check if it works continuously? I want to know if it was a one-time mess up or happens regurarly.

**Comment by Jenjen1324** [comment]
This is no longer an issue with the rebuilt site.
